pipeline {
    agent any

    tools {
        maven 'Maven3'   // must match the Maven installation name in Jenkins Global Tool Configuration
        jdk 'jdk11'      // must match the JDK installation name in Jenkins Global Tool Configuration
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/mrinalproxy/Mrinal-Kanti-Ghosh-Wipro-Capstone-Project.git'
            }
        }

        stage('Build & Test') {
            steps {
                // On Windows, use bat instead of sh
                bat 'mvn clean test'
            }
        }

        stage('Cucumber HTML Report') {
            steps {
                publishHTML([
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'target/cucumber-reports',
                    reportFiles: 'cucumber.html',
                    reportName: 'Cucumber Report'
                ])
            }
        }
    }

    post {
        always {
            // JUnit XML reports generated by Surefire
            junit 'target/surefire-reports/*.xml'
        }
        success {
            echo '✅ Build & Tests Passed!'
        }
        failure {
            echo '❌ Build Failed!'
        }
    }
}
